export type IndividualMembership = {
  id: string;
  personId: string;
  isActive: boolean;
  validUntil: Date;
  deletedAt: Date | null;
  type: string;
  membershipNumber: string | null;
  martialArtsOrg: string;
  profilePicture: string | null;
  createdAt: Date;
  updatedAt: Date;
  isExpired: boolean;
  isDeleted: boolean;
  isDraft: boolean;
  isMembershipCardRequested: boolean;
};
export type LeaderOfGroup = {
  id: string;
  groupName: string;
  membershipNumber: string;
  type: string;
  validUntil: Date;
  isExpired: boolean;
  isActive: boolean;
  isDeleted: boolean;
  createdAt: Date;
  updatedAt: Date;
  deletedAt: Date;
};
export type MemberOfGroups = {
  id: string;
  parentMembership: string;
  membershipNumber: string;
};
export type Person = {
  id: string;
  givenName: string;
  familyName: string;
  dob: Date;
  nationality: string;
  gender: string;
  residence: string;
  email: string | null;
  itfBackground: string;
  remarks: string | null;
  files: string[];
  createdAt: Date;
  updatedAt: Date;
};
export type Item = {
  id: string;
  orderId: string;
  item: string;
  price: number;
  quantity: number;
  personId: string;
  membershipId: string;
  groupMemberId: string;
  createdAt: Date;
  updatedAt: Date;
  Person: Person;
};
